sensor:
  - platform: template
    sensors:
      bleach_tank:
        friendly_name: "Bleach tank"
        value_template: "{{ states('input_number.bleach_tank')|round(2)}}"

  - platform: history_stats
    name: bleach_on_last_hour
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now().replace(minute=0).replace(second=0)}}'
    duration: 01:00:00

  - platform: history_stats
    name: bleach_on_last_48h
    entity_id: switch.orp
    state: 'on'
    type: time
    end: '{{now()}}'
    duration: 48:00:00

input_number:
  bleach_tank:
    min: 0
    max: 50
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:blood-bag
  bleach_concentration:
    min: 1
    max: 15
    step: .25
    unit_of_measurement: '%'
    icon: mdi:water-percent
    mode: box
  bleach_speed:
    min: 10
    max: 100
    step: 1
    unit_of_measurement: 'ml/min'
    icon: mdi:needle
  notify_bleach_high:
    min: 0
    max: 15
    step: 0.1
    unit_of_measurement: 'l/48h'
  notify_bleach_tank:
     min: 0
     max: 5
     step: 0.5
     unit_of_measurement: 'l'
     icon: mdi:flask-empty-outline
  bleach_inject:
    min: 0
    max: 20000
    step: 5
    unit_of_measurement: 'ml'
    icon: mdi:beaker
    mode: box

