sensor:
# Estimated sensor of effective Free Chlorine
  - platform: template
    sensors:
      e_fc:
        value_template: "{{ ( 0.23 * (1 + states('input_number.e_fc_adjust')|float / 100 ) * ( 14 - states('sensor.ph')|float) ** ( 1 / (400 - states('sensor.orp')|float) ) * ( states('sensor.ph')|float -4.1) ** ( ( states('sensor.orp')|float - 516)/145) + 10.0 ** ( (states('sensor.orp')|float + states('sensor.ph')|float * 70 -1282) / 40 ) ) |round(1) }}"
        unit_of_measurement: ppm
        # icon_template: mdi:chemical-weapon
        icon_template: mdi:react
        friendly_name: "Estimated FC"

input_number:
  e_fc_adjust:
    min: -100
    max: 100
    unit_of_measurement: '%'
    icon: mdi:react
    mode: box
  fc_target:
    min: 0
    max: 30
    step: 0.1
    mode: box
    unit_of_measurement: 'ppm'
    icon: mdi:react

