sensor:
  - platform: template
    sensors:
      muriatic_tank:
        friendly_name: "Muriatic tank"
        value_template: "{{ states('input_number.muriatic_tank')|round(2)}}"

  - platform: history_stats
    name: muriatic_on_last_hour
    entity_id: switch.ph
    state: 'on'
    type: time
    end: '{{now().replace(minute=0).replace(second=0)}}'
    duration: 01:00:00

  - platform: history_stats
    name: muriatic_on_last_48h
    entity_id: switch.ph
    state: 'on'
    type: time
    end: '{{now()}}'
    duration: 48:00:00


input_number:
  muriatic_tank:
    min: 0
    max: 30
    step: 0.1
    unit_of_measurement: 'l'
    icon: mdi:blood-bag
  muriatic_concentration:
    min: 5
    max: 30
    step: .1
    unit_of_measurement: '%'
    icon: mdi:water-percent
    mode: box
  muriatic_speed:
    min: 10
    max: 100
    step: 1
    unit_of_measurement: 'ml/min'
    icon: mdi:needle
  notify_muriatic_high:
    min: 0
    max: 5
    step: 0.1
    unit_of_measurement: 'l/48h'
  notify_muriatic_tank:
    min: 0
    max: 5
    step: 0.5
    unit_of_measurement: 'l'
    icon: mdi:flask-empty
  muriatic_inject:
    min: 0
    max: 10000
    step: 5
    unit_of_measurement: 'ml'
    icon: mdi:beaker
    mode: box

