sensor:
  - platform: statistics
    name: orp
    entity_id: sensor.ezo_orp
    max_age:
      minutes: 60
    precision: 0

  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: 0x62
#    offset: 78
    scan_interval: 10


