sensor:
  - platform: atlas_scientific
# For serial ports use:
#   port: /dev/ttyUSB0
# For I2C enter the hex device id
    port: 0x63
    scan_interval: 10

  - platform: statistics
    name: ph
    entity_id: sensor.ezo_ph
    max_age:
      minutes: 60
    # precision: 3

input_number:
  ph_target:
    min: 6.5
    max: 8.5
    step: 0.01
    unit_of_measurement: 'pH'
    icon: mdi:alpha-h-circle-outline
    mode: box

